---
title: "Weight Lifting Quality Assesment"
output: html_document
---

```{r}
library(caret)
library(plyr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(parallel)
library(reshape2)
```

```{r}
training <- read.csv("pml-training.csv")
testing <- read.csv("pml-testing.csv")
```

```{r}
carlitos_good_lifts <- training %>% 
  filter(user_name == "carlitos" & classe == "A") %>%
  mutate(raw_timestamp = ((raw_timestamp_part_1 - min(raw_timestamp_part_1)) * 1000000 + raw_timestamp_part_2) / 1000000.0)

belt_features <- c("roll_belt", "pitch_belt", "yaw_belt", "total_accel_belt",
                   "gyros_belt_x", "gyros_belt_y", "gyros_belt_z", 
                   "accel_belt_x", "accel_belt_y", "accel_belt_z", 
                   "magnet_belt_x", "magnet_belt_y", "magnet_belt_z")
arm_features <- c("roll_arm", "pitch_arm", "yaw_arm", "total_accel_arm", 
                  "gyros_arm_x", "gyros_arm_y", "gyros_arm_z", "accel_arm_x",
                  "accel_arm_y", "accel_arm_z", "magnet_arm_x", "magnet_arm_y",
                  "magnet_arm_z")
dumbbell_features <- c("roll_dumbbell", "pitch_dumbbell", "yaw_dumbbell",
                       "total_accel_dumbbell", "gyros_dumbbell_x", 
                       "gyros_dumbbell_y", "gyros_dumbbell_z", 
                       "accel_dumbbell_x", "accel_dumbbell_y", 
                       "accel_dumbbell_z", "magnet_dumbbell_x", 
                       "magnet_dumbbell_y", "magnet_dumbbell_z")
forearm_features <- c("roll_forearm", "pitch_forearm", "yaw_forearm",
                      "total_accel_forearm", "gyros_forearm_x", 
                      "gyros_forearm_y", "gyros_forearm_z", "accel_forearm_x",
                      "accel_forearm_y", "accel_forearm_z", "magnet_forearm_x",
                      "magnet_forearm_y", "magnet_forearm_z")

carlitos_good_lifts.narrow <- melt(carlitos_good_lifts, 
                                   id.vars = c("raw_timestamp"), 
                                   measure.vars = c(belt_features,
                                                    arm_features,
                                                    dumbbell_features,
                                                    forearm_features))
carlitos_good_lifts.narrow$source <- 
  ifelse(carlitos_good_lifts.narrow$variable %in% belt_features, "belt", 
         ifelse(carlitos_good_lifts.narrow$variable %in% arm_features, "arm",
                ifelse(carlitos_good_lifts.narrow$variable %in% dumbbell_features, "dumbbell",
                       ifelse(carlitos_good_lifts.narrow$variable %in% forearm_features, "forearm", 
                              "UNKNOWN"))))

carlitos_good_lifts.narrow$variable <- 
  gsub("_(belt|arm|dumbbell|forearm)", "", carlitos_good_lifts.narrow$variable)

window_markers <- carlitos_good_lifts %>%
  filter(new_window == "yes") %>%
  mutate(raw_timestamp = ((raw_timestamp_part_1 - 1323084231) * 1000000 + raw_timestamp_part_2) / 1000000.0) %>%
  select(raw_timestamp)
```


```{r}
ggplot(carlitos_good_lifts.narrow,  aes(raw_timestamp, value, color=variable)) + 
  facet_wrap(~source, ncol = 1) +
  geom_line() + 
  scale_x_continuous(breaks = 1:40) + 
  geom_vline(data=window_markers, aes(xintercept=raw_timestamp), linetype="longdash", alpha = 0.3)
```

```{r}
create_sliding_window_summary_fn <- function(window_size, overlap) {
  return(function(df) {
    df <- mutate(df, raw_timestamp = ((raw_timestamp_part_1 - min(raw_timestamp_part_1)) * 1000000 + raw_timestamp_part_2) / 1000000.0)
    sm = list()
    for(x in seq(min(df$raw_timestamp), max(df$raw_timestamp), window_size - overlap)) {
      s <- filter(df, raw_timestamp >= x & raw_timestamp < raw_timestamp + window_size)
      ndf = data.frame(classe=first(df$classe))
      for (f in c(belt_features, arm_features, dumbbell_features, forearm_features)) {
        ndf[,paste("max", f, sep="_")] = max(s[,f])
        ndf[,paste("min", f, sep="_")] = min(s[,f])
        ndf[,paste("avg", f, sep="_")] = mean(s[,f])
        ndf[,paste("var", f, sep="_")] = var(s[,f])
      }
      sm[[length(sm) + 1]] = ndf
    }
    sm_all <- rbind_all(sm)
    print(dim(sm_all))
    return(sm_all)
  })
}

z = list()
for (x in seq(0.5, 5.0, 0.5)) {
  for (overlap in seq(0, x - 0.5, 0.5)) {
    print(paste("Proccessing window size", x, "overlap", overlap))
    z[[paste("win", x, "overlap", overlap, sep = "-")]] <- 
      rbind_all(dlply(training, 
                      .(user_name, classe), 
                      create_sliding_window_summary_fn(x, overlap)))
  }
}
```

```{r}
fitControlRf <- trainControl(method = "cv", number = 10)
set.seed(94610348)
fit_rf <- mclapply(seq_along(z), function(i) {
  df <- z[[i]]
  print(paste("Fitting rf", names(z)[[i]]))
  return(list(fit=train(classe ~ .,
                        data = df,
                        method = "rf",
                        trControl = fitControlRf),
              window=names(z)[[i]]))
}, mc.cores = 8)
```

```{r}
fitControlNn <- trainControl(method = "cv", number = 10)
my.grid <- expand.grid(.decay = c(0, 1e-4, 1e-1, 1), .size = c(15, 30, 50))

set.seed(10482349)
fit_nn <- mclapply(seq_along(z), function(i) {
  df <- z[[i]]
  print(paste("Fitting nn", names(z)[[i]]))
  return(list(fit=train(classe ~ ., 
                        data = df, 
                        method = "nnet", 
                        trControl = fitControlNn, 
                        trace = FALSE, 
                        tuneGrid = my.grid,
                        MaxNWts = 10000,
                        preProcess = c("center", "scale", "pca")),
              window=names(z)[[i]]))
  }, mc.cores = 8)
```

```{r}
accuracies <- data.frame(sapply(fit_rf, function(f) max(f$fit$results$Accuracy)))
accuracies$window <- sapply(fit_rf, function(f) f$window)
names(accuracies)[[1]] <- "accuracy"
accuracies <- arrange(accuracies, accuracy)

ggplot(accuracies, aes(window, accuracy)) + geom_point() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
# resampling
# 1.5o1
# 3.5o5 (best) ~75
# 3.0o0
# 4.5o1.5
# 4.5o3
# 4.5o4
# 5.0o2

# k-fold cross-validation
# 3.5o0.5
# 3.0o0
# 4.0o1 (best) ~78
# 5.0o2

# rf
# 47 0.9916235   win-4.5-overlap-4
# 48 0.9922150   win-0.5-overlap-0
# 49 0.9940295   win-3-overlap-2.5
# 50 0.9940401   win-3.5-overlap-3
# 51 0.9951915   win-5-overlap-4.5
# 52 0.9952024   win-1-overlap-0.5
# 53 0.9952131   win-4-overlap-3.5
# 54 0.9958045   win-1.5-overlap-1
# 55 0.9964213   win-2.5-overlap-2

# nnet size=20 accuracy ~60%
# nnet size=20 w/ feature scaling ~99.3
#    50 0.9910141   win-2-overlap-1.5
#    51 0.9916201   win-2.5-overlap-2
#    52 0.9916201   win-4.5-overlap-4
#    53 0.9928177   win-5-overlap-4.5
#    54 0.9933841   win-3.5-overlap-3
#    55 0.9933950   win-1-overlap-0.5
# nnet size=20 w/ feature scaling, pca ~98.7
# nnet size=50 w/ feature scaling, pca ~99.2
# 50 0.9892210   win-3.5-overlap-3
# 51 0.9898092   win-0.5-overlap-0
# 52 0.9904082   win-2-overlap-1.5
# 53 0.9904369   win-4.5-overlap-4
# 54 0.9916202   win-1.5-overlap-1
# 55 0.9921936   win-3-overlap-2.5

```

```{r}
accuracies <- data.frame(sapply(fit_nn, function(f) max(f$fit$results$Accuracy, na.rm = TRUE)))
accuracies$window <- sapply(fit_rf, function(f) f$window)
names(accuracies)[[1]] <- "accuracy"
accuracies <- arrange(accuracies, accuracy)

ggplot(accuracies, aes(window, accuracy)) + geom_point() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
